#!/bin/zsh

start-docker () {
    docker-compose build && docker-compose up
}

rebuild-venv () {
    rm -rf server/venv &&
    python3 -m venv server/venv &&
    source server/venv/bin/activate &&
    pip install -r server/src/requirements.txt &&
    deactivate
}


$1

#    "start": "docker-compose build && docker-compose up",
 #   "stop": "docker-compose down",
 #   "remove-venv": "rm -rf server/venv",
 #   "build-venv": "python3 -m venv server/venv",
 #   "install-venv": "pip install -r server/src/requirements.txt",
  #  "rebuild-venv": "rm -rf server/venv && python3 -m venv server/venv && source server/venv/bin/activate && pip install -r server/src/requirements.txt && deactivate"