swagger: "2.0"
info:
  description: "API Specifications for Python Anywhere Flask"
  version: "1.0.0"
  title: "Python Anywhere Flask API"
host: "localhost:5000"
tags:
- name: "quotes"
  description: "Everything about your quotes"
schemes:
- "http"
paths:
  /quotes:
    get:
      tags:
      - "quotes"
      summary: "Return all quotes"
      description: ""
      operationId: "getQuotes"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Quote"
    post:
      tags:
      - "quotes"
      summary: "Create new quote"
      description: ""
      operationId: "postQuotes"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Create quote object"
        required: true
        schema:
          $ref: "#/definitions/Quote"
      responses:
        "201":
          description: "Created"
  /quotes/{id}:
    parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the quote
    get:
      tags:
      - "quotes"
      summary: "Return quote by Id"
      description: ""
      operationId: "getQuoteById"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Quote"
    delete:
      tags:
      - "quotes"
      summary: "Delete quote by Id"
      description: ""
      operationId: "deleteQuoteById"
      produces:
      - "application/json"
      responses:
        "204":
          description: "No content"
  /quotes/random:
    get:
      tags:
      - "quotes"
      summary: "Get random quote"
      description: ""
      operationId: "getRandomQuote"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Quote"
        "400":
          description: "Invalid status value"
definitions:
  Quote:
    type: "object"
    required:
    - "body"
    - "author"
    - "category"
    properties:
      body:
        type: "string"
      author:
        type: "string"
      category:
        type: "string"
      subcategory:
        type: "string"
      numeral:
        type: "string"
    xml:
      name: "Quote"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"